import { parseURDF, serializeURDF } from "../parsing/urdfParser";
import { parseMeshReference } from "../mesh/meshPaths";
import {
  buildPackageRootsFromRepositoryFiles,
  normalizeRepositoryPath,
  repositoryDirname,
  type RepositoryFileEntry,
} from "../repository/repositoryMeshResolution";

const normalizeAbsolutePath = (value: string): string =>
  value.replace(/\\/g, "/").replace(/\/+/g, "/");

const makeRelativePath = (fromDir: string, toPath: string): string => {
  const from = normalizeRepositoryPath(fromDir);
  const to = normalizeRepositoryPath(toPath);
  if (!from) return to;

  const fromParts = from.split("/").filter(Boolean);
  const toParts = to.split("/").filter(Boolean);
  let common = 0;
  while (common < fromParts.length && common < toParts.length) {
    if (fromParts[common] !== toParts[common]) break;
    common += 1;
  }

  const ups = Array.from({ length: fromParts.length - common }, () => "..");
  const down = toParts.slice(common);
  return [...ups, ...down].join("/") || ".";
};

const findUniqueFileByBasename = <T extends RepositoryFileEntry>(
  files: T[],
  absolutePath: string
): T | null => {
  const basename = normalizeAbsolutePath(absolutePath)
    .split("/")
    .filter(Boolean)
    .pop()
    ?.toLowerCase();
  if (!basename) return null;

  const matches = files.filter((file) => {
    if (file.type !== "file") return false;
    return file.path.split("/").filter(Boolean).pop()?.toLowerCase() === basename;
  });

  return matches.length === 1 ? matches[0] : null;
};

const findRepositoryFileByAbsoluteSuffix = <T extends RepositoryFileEntry>(
  files: T[],
  absolutePath: string
): T | null => {
  const normalizedAbsolute = normalizeAbsolutePath(absolutePath).toLowerCase();
  let best: T | null = null;
  let bestLength = -1;

  for (const file of files) {
    if (file.type !== "file") continue;
    const normalizedPath = normalizeRepositoryPath(file.path);
    if (!normalizedPath) continue;
    const loweredPath = normalizedPath.toLowerCase();
    if (
      normalizedAbsolute === loweredPath ||
      normalizedAbsolute.endsWith(`/${loweredPath}`)
    ) {
      if (loweredPath.length > bestLength) {
        best = file;
        bestLength = loweredPath.length;
      }
    }
  }

  return best ?? findUniqueFileByBasename(files, absolutePath);
};

const findPackageReferenceForPath = (
  resolvedPath: string,
  packageRoots: Record<string, string[]>
): string | null => {
  const normalized = normalizeRepositoryPath(resolvedPath);
  if (!normalized) return null;

  let best: { pkg: string; root: string } | null = null;
  for (const [pkg, roots] of Object.entries(packageRoots)) {
    for (const root of roots) {
      const normalizedRoot = normalizeRepositoryPath(root);
      if (!normalizedRoot) continue;
      if (normalized === normalizedRoot || normalized.startsWith(`${normalizedRoot}/`)) {
        if (!best || normalizedRoot.length > best.root.length) {
          best = { pkg, root: normalizedRoot };
        }
      }
    }
  }

  if (!best) return null;
  const relative = normalized.slice(best.root.length).replace(/^\/+/, "");
  return relative ? `package://${best.pkg}/${relative}` : `package://${best.pkg}`;
};

export const stabilizeExpandedXacroUrdf = <T extends RepositoryFileEntry>(
  urdfContent: string,
  entryPath: string,
  files: T[]
): { urdf: string; correctionCount: number } => {
  const normalizedEntryPath = normalizeRepositoryPath(entryPath);
  const rewrittenComment = urdfContent.replace(
    /(autogenerated by xacro from )([^|]+?)(\s+\|)/i,
    (_match, prefix: string, _originalPath: string, suffix: string) =>
      `${prefix}${normalizedEntryPath || entryPath}${suffix}`
  );

  const parsed = parseURDF(rewrittenComment);
  if (!parsed.isValid) {
    return { urdf: rewrittenComment, correctionCount: 0 };
  }

  const entryDir = repositoryDirname(normalizedEntryPath || entryPath);
  const packageRoots = buildPackageRootsFromRepositoryFiles(files);
  let correctionCount = 0;

  for (const mesh of Array.from(parsed.document.querySelectorAll("mesh"))) {
    const filename = mesh.getAttribute("filename")?.trim();
    if (!filename) continue;

    const refInfo = parseMeshReference(filename);
    if (!(refInfo.scheme === "file" && refInfo.isAbsoluteFile)) continue;

    const matchedFile = findRepositoryFileByAbsoluteSuffix(files, refInfo.path);
    if (!matchedFile) continue;

    const normalizedPath = normalizeRepositoryPath(matchedFile.path);
    if (!normalizedPath) continue;

    const packageRef = findPackageReferenceForPath(normalizedPath, packageRoots);
    const corrected = packageRef || makeRelativePath(entryDir, normalizedPath);
    if (!corrected || corrected === filename) continue;

    mesh.setAttribute("filename", corrected);
    correctionCount += 1;
  }

  return {
    urdf: serializeURDF(parsed.document),
    correctionCount,
  };
};
